#!/bin/bash -v

#remove any trailing slash
dirToProcess=$(echo $1 | sed 's/[/]\+$//g')

if [ ! -d "$dirToProcess" ]; then
	echo "'$dirToProcess' is not a directory"
fi

THIS_DIR=$(dirname -- "$(readlink -f -- "$0")"
source $THIS_DIR/syncfuncs.bashrc

for item in $(ls $dirToProcess); do
	BackupToAws ~/family/synced/docs/$items
done

