#!/bin/bash

#remove any trailing slash
dirToProcess=$(echo $1 | sed 's/[/]\+$//g')
archiveOpt=$2
snapshotOpt=$3

THIS_DIR=$(dirname -- "$(readlink -f -- "$0")")
. $THIS_DIR/syncfuncs.bashrc

for item in $(ls $dirToProcess); do
	Backup $dirToProcess/$item $archiveOpt $snapshotOpt
done

