#!/bin/bash -v

tar cj ~/storage/synced/docs/keith | gpg -c --batch --passphrase-fd 1 --passphrase-file /home/keith/.synced-passphrase > ice-keith-`date +%Y%m%d`.tar.bz2.gpg && trickle -s -u 128 s3cmd put ice-keith-*gpg s3://totallyawesomebucket && rm ice-keith*
